(defun bi-search (lst l u d)
  (format t "-------------~%")
  (format t "l: ~d~%" l)
  (format t "u: ~d~%" u)
  (if (>= l u)
      -1)
  (let* ((m (floor (+ l u) 2))
         (mid-elem (nth m lst)))
    (format t "~d~%" m)
    (if (equal mid-elem d)
        m
        (if (< mid-elem d)
            (bi-search lst (+ m 1) u d)
            (bi-search lst l (- m 1) d)))))
