#!/bin/bash

cmtmsg="BPC-1234 how can i go on"

#-----------------------------------------------------------
# usage function
#-----------------------------------------------------------
function usage {
    echo "./$(basename $0) -h           --> shows usage"
    echo "./$(basename $0) -a item      --> add item to .gitignore file"
    echo "./$(basename $0) -d item      --> rm  item if it is in .gitignore file"
    echo "./$(basename $0) -p (cmt msg) --> rm  add, commit, then push"
}

#-----------------------------------------------------------
# add item to .gitignore file
#-----------------------------------------------------------
function add_item_to_gitignore () {
    git config --global alias.root 'rev-parse --show-toplevel'
    cd $(git root)
    if [[ -f .gitignore ]]; then
	echo $1 >> .gitignore
    else
	touch .gitignore
	echo $1 > .gitignore
    fi
}

#-----------------------------------------------------------
# remove item if it appears in .gitignore file
#-----------------------------------------------------------
function rm_item_in_gitignore () {
    git config --global alias.root 'rev-parse --show-toplevel'
    cd $(git root)
    if [[ -f .gitignore ]]; then
	sed s/$1// .gitignore > .gitignore.bak
	mv .gitignore.bak .gitignore
    fi
}

optstr="ha:d:p"

while getopts ${optstr} arg; do
    case ${arg} in
	h)
	    echo "Showing usage!"
	    usage
	    ;;
	a)
	    echo "Adding item ${2} to .gitignore file"
	    add_item_to_gitignore $2
	    exit 0
	    ;;
	d)
	    echo "Remove item ${2} if it appears in .gitignore file"
	    rm_item_in_gitignore $2
	    exit 0
	    ;;
	p)
	    echo "Add, commit and push"
	    git add .
	    if [[ -z $2 ]];then
		git commit -m "${cmtmsg}"
	    else
		git commit -m $2
	    fi
	    git config --global credentail.helper 'cache --timeout 720000'
	    git push
	    exit 0
	    ;;
	?)
	    echo "Invalid option: -${OPTARG}."
	    exit 2
	    ;;
    esac
done
